# Generated by Django 5.0.4 on 2024-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(default='@email', max_length=50, unique=True, verbose_name='آدرس ایمیل')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='تلفن')),
                ('message', models.TextField(verbose_name='پیام شما')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل ما')),
                ('loc', models.TextField(blank=True, null=True, verbose_name='موقعیت ما')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تماس با ما')),
                ('iframe', models.TextField(blank=True, help_text='لینک src مپ را وارد کنید', null=True, verbose_name='مپ')),
            ],
            options={
                'verbose_name': ' اطلاعات تماس با ما ',
                'verbose_name_plural': 'اطلاعات تماس با ما',
            },
        ),
    ]
