# Generated by Django 5.0.4 on 2024-04-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_logs', '0002_rename_otpcodemodel_donatelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatelog',
            options={'ordering': ('-date',)},
        ),
    ]
