# Generated by Django 5.0.4 on 2024-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_logs', '0003_alter_donatelog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatelog',
            options={'ordering': ('-date',), 'verbose_name': 'اطلاعاتی', 'verbose_name_plural': 'اطلاعات'},
        ),
        migrations.AddField(
            model_name='donatelog',
            name='currency',
            field=models.CharField(choices=[('TOMAN', 'toman'), ('DOLLAR', 'dollar'), ('EURO', 'euro'), ('POUND', 'pound'), ('IQD', 'iqd'), ('LIRA', 'lira')], default='TOMAN', max_length=9),
        ),
    ]
