# Generated by Django 5.0.4 on 2024-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_logs', '0005_donatelog_gold_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatelog',
            name='currency',
            field=models.CharField(choices=[('IRR', 'irr'), ('DOLLAR', 'dollar'), ('EURO', 'euro'), ('POUND', 'pound'), ('IQD', 'iqd'), ('LIRA', 'lira')], default='TOMAN', max_length=9),
        ),
    ]
