# Generated by Django 5.0.4 on 2024-05-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcodemodel',
            options={'verbose_name': 'کد تاییدی', 'verbose_name_plural': 'کد های تایید'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربری', 'verbose_name_plural': 'کاربران'},
        ),
    ]
