# Generated by Django 5.0.4 on 2024-05-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpcodemodel_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_donate',
            field=models.FloatField(default=0),
        ),
    ]
