# Generated by Django 5.0.4 on 2024-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name_plural': 'ایمیل های خبرنامه',
            },
        ),
        migrations.CreateModel(
            name='NewsletterMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'خبر جدید',
            },
        ),
    ]
