# Generated by Django 5.0.4 on 2024-04-21 23:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/blog/%Y/%m/%d', verbose_name='تصویر مقاله')),
                ('body', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, unique=True, verbose_name='اسلاگ')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='به\u200cروز شده')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ ها',
                'ordering': ('-updated',),
            },
        ),
    ]
