# Generated by Django 5.0.4 on 2024-04-24 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_options_blogmodel_lovely'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='commentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('body', models.TextField(verbose_name='متن')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='منتشر شده')),
                ('isActive', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='blog.blogmodel', verbose_name='برای وبلاگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyText', models.TextField(verbose_name='متن جواب')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='blog.commentmodel', verbose_name='برای نظر')),
            ],
            options={
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
    ]
