# Generated by Django 5.0.4 on 2024-05-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentmodel_replycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-updated',), 'verbose_name': 'وبلاگی', 'verbose_name_plural': 'بلاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'نظری', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'verbose_name': 'پاسخی', 'verbose_name_plural': 'پاسخ ها'},
        ),
    ]
